package com.demersonpolli.patterns;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.openfeign.EnableFeignClients;


/**
 * Spring Boot project generated by Spring Initializr.
 * The selected modules was:
 *  - Spring Data JPA
 *  - Spring Web
 *  - H2 Database
 *  - OpenFeign
 */
@EnableFeignClients
@SpringBootApplication
public class PatternsApplication {
	public static void main(String[] args) {
		SpringApplication.run(PatternsApplication.class, args);
	}
}
